simple_user:
    resource: "@SimpleUserBundle/Resources/config/routing.yml"
    prefix:   /

super_user:
    resource: "@SuperUserBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"