super_user_homepage:
    path:     /
    defaults: { _controller: SuperUserBundle:Default:index }
super_user_conseils_affiche:
    path:     /conseils/ajout
    defaults: { _controller: SuperUserBundle:Conseils:Ajout }
super_user_userpr_affiche:
    path:     /affichepr
    defaults: { _controller: SuperUserBundle:UserPr:Affiche }
super_user_formation_affiche:
     path:     /formation/ajout
     defaults: { _controller: SuperUserBundle:Formation:Ajout }
super_user_soins_affiche:
     path:     /soins/ajout
     defaults: { _controller: SuperUserBundle:Soins:Ajout }
